export const SMALL_ACHIEVABLE_GOALS = [
  "Quick first step",
  "Call every ball",
  "Talk between plays",
  "Reset after errors",
  "See the hitter",
  "Track the setter",
  "Beat the ball",
  "Finish my platform",
  "Move before contact",
  "Stay low longer",
  "Serve with intent",
  "Aim my serve",
  "Attack aggressively",
  "Swing to space",
  "Cover every hitter",
  "Read before moving",
  "Help a teammate",
  "Ask one question",
  "Try one adjustment",
  "Stay engaged",
  "Celebrate teammates",
  "Breathe and reset",
  "Commit to choices",
  "Play brave",
  "Compete every rally",
  "Early ready position",
  "Move my feet",
  "Strong platform",
  "Quiet hands",
  "Fast transition",
  "Finish every play",
  "Stay balanced",
  "Read the server",
  "Watch the ball",
  "Trust my training",
  "Be more decisive",
  "Take good angles",
  "Recover quickly",
  "Stay present",
  "Win the next ball",
  "Attack smart",
  "Hit high hands",
  "Deep corner serve",
  "Tough float serve",
  "Serve tough",
  "Pass to target",
  "Set with intention",
  "Beat the block",
  "Press over net",
  "Seal the block",
  "Strong pursuit",
  "Protect the tip",
  "Chase every ball",
  "Be available",
  "Stay calm",
  "Next play mindset",
  "Keep it simple",
  "One point at a time",
  "Be a great teammate",
  "Bring encouragement",
  "Lead with energy",
  "Stay coachable",
  "Focus on effort",
  "Compete with joy",
  "Stay confident"
];
